python:
  - 3.6
  - 3.7
  - 3.8
language: python
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install git+https://github.com/lgarrison/asdf.git
  - gcc --version
install:
  - pip install .
  - cd pipe_asdf && make
script:
  - pytest
  - cd tests && ./test_pipe_asdf.sh
